" pathogen
execute pathogen#infect()
set laststatus=2

" colors
syntax on
let g:lightline = {'colorscheme': 'jellybeans'}

" misc
set number
filetype plugin indent on
set hlsearch
set incsearch
set smartcase

" Basic
set autoread                                     " reload on external file changes
set backspace=indent,eol,start                   " backspace behaviour
set clipboard=unnamed,unnamedplus                " enable clipboard
set encoding=utf8                                " enable utf8 support
set hidden                                       " hide buffers, don't close
set mouse=a                                      " enable mouse support
set nowrap                                       " disable wrapping
set number                                       " show line numbers

if  !has('nvim')
    set term=xterm-256color                          " terminal type
endif

set wildmenu wildmode=longest:full,full          " wildmode settings
set wildcharm=<Tab>                              " wildmenu character
set showcmd                                      " show command keys
set splitbelow splitright                        " better split behaviour
set autochdir                                    " switch to files local directory

" UI
filetype plugin indent on                        " enable filetype detection
set listchars=eol:¶,trail:•,tab:▸\               " whitespace characters
set scrolloff=999                                " center cursor position vertically
set showbreak=¬\                                 " Wrapping character
set showmatch                                    " show matching brackets
syntax on                                        " enable syntax highlightning

" Tabs & Indentation
set autoindent expandtab                         " autoindentation & tabbing
set shiftwidth=4 softtabstop=4 tabstop=4         " 1 tab = 2 spaces

" Search
set hlsearch ignorecase incsearch smartcase      " search options

" Undo & Backup
set nobackup noswapfile nowritebackup            " disable backup/swap files
set undofile undodir=~/.vim/undo undolevels=9999 " undo options

" Performance Tuning
set lazyredraw                                   " enable lazyredraw
set nocursorline                                 " disable cursorline
set ttyfast                                      " enable fast terminal connection

" Custom Commands
cnoreabbrev w!! w !sudo tee > /dev/null %|       " write file with sudo
