eval "$(/opt/homebrew/bin/brew shellenv)"
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

#set PATH so it includes python --user binaries
if [ -d "$HOME/Library/Python/3.9/bin" ] ; then
    PATH="$HOME/Library/Python/3.9/bin:$PATH"
fi

